pull_request_rules:
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=github-actions[bot]
      - status-success~=Build and Test
      - body~=labels:.*semver-patch.*
    actions:
      merge:
        method: merge
